### ISSUE TITLE
Have you ever tried this method on 3D lidar?

### ISSUE THREAD

**Issue by DeepDuke** [PRBonn/ir-mcl#5]

**Comment by KuangHaofei** [comment]
Hi @DeepDuke,

Thanks for your interest in our work. To answer your question:

We have not conducted experiments with 3D LiDAR for this project. The primary objective of this work was to utilize Monte Carlo Localization (MCL) in 2D environments. Therefore, the use of a Neural Radiance Fields (NeRF) network structure and a rendering-based observation model was sufficient to meet our needs in terms of performance and speed.

If you are considering the use of 3D LiDAR, the network structure and rendering-based observation model used in this project may be too inefficient. You might want to consider using grid feature-based methods or implicit representations based on Signed Distance Fields (SDF). I recommend checking out two other projects from our lab that might be of interest:

[SHINE-Mapping: Large-Scale 3D Mapping Using Sparse Hierarchical Implicit Neural Representations](https://www.ipb.uni-bonn.de/wp-content/papercite-data/pdf/zhong2023icra.pdf)

[LocNDF: Neural Distance Field Mapping for Robot Localization](https://www.ipb.uni-bonn.de/wp-content/papercite-data/pdf/wiesmann2023ral-icra.pdf)

I hope this information is helpful. Let me know if you have any other questions! Thanks!

**Comment by DeepDuke** [comment]
TKS!
